name: spice
channels:
  - conda-forge
  - openalea3
dependencies:
  - python
  - openalea.lpy
  - openalea.plantgl
  - oawidgets
  - embree
  - make
  - cxx-compiler
  - cmake
  - tbb
  - tbb-devel
  - llvm-openmp
  - tsl_robin_map
  - pip
  - pip:
      - -e ..[doc,notebook]